/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is automatically generated by Next.js when dependencies are installed.
// Keep it in the repository so TypeScript resolves Next.js types cleanly in editors.
